kind: Deployment
apiVersion: apps/v1
metadata:
    name: doom-client
    namespace: prod
spec:
    replicas: 1
    selector:
      matchLabels:
        name: doom-client
    template:
      metadata:
        labels:
          name: doom-client
      spec:
        containers:
        - name: doom-client
          image: adamsandor83/doom-client:1
          ports:
          - containerPort: 8080
            name: web
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 1
          env:
            - name: DOOM_STATE_SERVICE_URL
              value: http://doom-state
            - name: DOOM_ENGINE_SERVICE_URL
              value: http://doom-engine
            - name: DOOM_STATE_SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "doom-state-secrets"
                  key: "doom-client-password"
---
kind: Service
apiVersion: v1
metadata:
    name: doom-client
    namespace: prod
spec:
    ports:
    - name: web
      port: 80
      targetPort: 8080
    selector:
      name: doom-client
    type: NodePort